### ISSUE TITLE
next is not defined 

### ISSUE THREAD

**Issue by Kiranyellu** [gugui3z24/meanstacktutorial#8]
/var/www/html/meanstacktutorial/app/models/user.js:17
        next();
        ^

ReferenceError: next is not defined
    at bcrypt.hash (/var/www/html/meanstacktutorial/app/models/user.js:17:9)
    at /var/www/html/meanstacktutorial/node_modules/bcrypt-nodejs/bCrypt.js:631:3
    at _combinedTickCallback (internal/process/next_tick.js:131:7)
    at process._tickCallback (internal/process/next_tick.js:180:9)
please help me out ..thank you in advance

**Comment by Kiranyellu** [comment]
![image](https://user-images.githubusercontent.com/31812511/37138512-5b99487c-22d0-11e8-98ef-a5543543090a.png)
